version: "3.8"
services:
    chatbot-ui:
        image: chatgpt-ui:latest
        restart: unless-stopped
        environment:
            OPENAI_API_HOST: "http://localhost:8000"
        ports:
            - 3000:3000
    vicuna:


