version: "3.8"
services:
    chatbot-ui:
        image: chatgpt-ui:latest
        restart: unless-stopped
        environment:
            OPENAI_API_HOST: "http://vicuna:8000"
        ports:
            - 3000:3000
    vicuna:
        image: llama-server:latest
        restart: unless-stopped
        environment:
            MODEL: "./llama.cpp/models/ggml-vic7b-q4_0.bin"
            HOST: "0.0.0.0"
            PORT: "8000"
        ports:
            - 8000:8000
        volumes:
            - ./llama.cpp/models/ggml-vic7b-q4_0.bin:/llama.cpp/models/ggml-vic7b-q4_0.bin
        deploy:
            resources:
                limits:
                    cpus: '4'
                    memory: 6G
                reservations:
                    cpus: '3'
                    memory: 6G



