version: "3.8"
services:
    chatbot-ui:
        build: ./chatbot-ui
        restart: unless-stopped
        environment:
            OPENAI_API_HOST: "http://vicuna-server:8000"
            MODEL_PATH: "./models/ggml-vic7b-q4_0.bin"
            MODEL_NAME: "Vicuna"
            NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT: "You are a friendly chatbot. Follow the user's instructions carefully. Respond using markdown."
        ports:
            - 3000:3000
    vicuna-server:
        build: ./vicuna-server
        restart: unless-stopped
        environment:
            MODEL: "./models/ggml-vic7b-q4_0.bin"
            HOST: "0.0.0.0"
            PORT: "8000"
        ports:
            - 8000:8000
        volumes:
            - ./models:/models
        deploy:
            resources:
                limits:
                    cpus: '4'
                    memory: 6G
                reservations:
                    cpus: '3'
                    memory: 6G



